feat: minor improvement to the script/unit and updating the ignore file

diff --git a/script/unit b/script/unit
--- a/script/unit
+++ b/script/unit
@@ -18,6 +18,8 @@ xcodebuild test-without-building \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6' 2>&1 | /usr/local/bin/ocunit2junit
 
+RC=$?
+
 echo "Collecting code coverage..."
 /usr/local/bin/slather
 
@@ -28,4 +30,10 @@ cp -a test-reports/. test_results/unit/
 cp -a cobertura/cobertura.xml test_results/cobertura/coverage.xml
 rm -rf test-reports
 rm -rf cobertura
-echo "DONE."
+
+if [ $RC = 0 ]; then
+    echo "Unit tests passed"
+    exit $RC
+else
+    echo "Unit tests failed"
+    exit $RC
