fix: making sure that script/unit exits 1 if tests failed

diff --git a/script/unit b/script/unit
--- a/script/unit
+++ b/script/unit
@@ -2,12 +2,7 @@
 CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 PARRENT_DIR="$(dirname "$current_dir")"
 
-echo "Cleaning the environment..."
-rm -rf $PARRENT_DIR/MapillarySDK/Podfile.lock $PARRENT_DIR/MapillarySDK/Pods $PARENT_DIR/MapillarySDK/MapillarySDK.xcworkspace
-
-echo "Generating workspace"
 export LANG=en_US.UTF-8
-pod install --project-directory=$PARRENT_DIR/MapillarySDK
 
 echo "Running tests..."
 xcodebuild test-without-building \
@@ -28,4 +23,11 @@ cp -a test-reports/. test_results/unit/
 cp -a cobertura/cobertura.xml test_results/cobertura/coverage.xml
 rm -rf test-reports
 rm -rf cobertura
-echo "DONE."
+echo "DONE.
+
+if [ $RC = 0 ]; then
+    echo "Unit tests passed"
+else
+    echo "Unit tests failed"
+    exit 1
+fi"
